apiVersion: v1
kind: Secret
metadata:
  name: azure-service-bus-secrets2
type: Opaque
data:
  connectionString2: RW5kcG9pbnQ9c2I6Ly9leGFtcGxlLXNlcnZpY2VidXMuc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1Sb290TWFuYWdlU2hhcmVkQWNjZXNzS2V5O1NoYXJlZEFjY2Vzc0tleT1IOHZOKzl1TDNxZkprNzNTOXhRd0tjTTVrWVp6MGIyKzNFZFZRaFhHWnNZPQ==

---

apiVersion: v1
kind: Secret
metadata:
  name: order-queue-secret
type: Opaque
data:
  ORDER_QUEUE_PASSWORD: UEBzc3cwcmQheEE3I0xkMjl6S3dRUDh2TmNV
