apiVersion: v1
kind: Secret
metadata:
  name: azure-servicebus-secret
type: Opaque
data:
  connectionString: "RW5kcG9pbnQ9c2I6Ly9iZXN0YnV5bmFtZXNwYWNlLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9c2VuZGVyO1NoYXJlZEFjY2Vzc0tleT1xVTNwa2k0cTlwY0RuNWlmK2ZjeVBJU2lXMDVzblFVbGErQVNiS3hUQnVvPTtFbnRpdHlQYXRoPW9yZGVycw=="