apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: your-order-service-image:latest
          env:
            - name: AZURE_SERVICE_BUS_NAMESPACE
              value: "your-servicebus-namespace"
            - name: AZURE_SERVICE_BUS_QUEUE_NAME
              value: "orders"
            - name: AZURE_SERVICE_BUS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: azure-service-bus-secret
                  key: connection-string
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
    spec:
      containers:
        - name: makeline-service
          image: your-makeline-service-image:latest
          env:
            - name: AZURE_SERVICE_BUS_NAMESPACE
              value: "your-servicebus-namespace"
            - name: AZURE_SERVICE_BUS_QUEUE_NAME
              value: "orders"
            - name: AZURE_SERVICE_BUS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: azure-service-bus-secret
                  key: connection-string
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-service-bus-secret
stringData:
  connection-string: "your-azure-service-bus-connection-string"
